name: Auto tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - all_tests
          - smoke_tests
          - regression_tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: all_tests
        if: "github.event.inputs.deployment_target == 'all_tests'"
        run: pytest --alluredir==allure_tests
      - name: smoke_tests
        if: "github.event.inputs.deployment_target == 'smoke_tests'"
        run: pytest tests/ -s -v -m "smoke tests" --alluredir==allure_tests
      - name: regression_tests
        if: "github.event.inputs.deployment_target == 'regression_tests'"
        run: pytest tests/ -s -v -m "regression tests" --alluredir==allure_tests
